### ISSUE TITLE
Must/should/nice have

### ISSUE THREAD

**Issue by mistercrunch** [apache-superset/docs#18]
## Must have
- [x] routes look auto-generated (in a bad way) in many places, especially in the docs. I fixed many of the `mdx` files put there's more work to be done
- [x] html `<title/>` not set, I added a `Welcome | Superset` default one, but we need to do a light pass on this and have `Documentation | Superset` and `Community | Superset` and such, should be super easy
- [x] most text files are going way over 100 char width, especially the content and mdx files, this makes files harder to edit and git history doesn't work well this way. This should be easy to automate (many IDEs will fix that as you open the files)
- [x] lots of trailing whitespaces and similar lint, let's setup `eslint`
- [x] docs content seem odd, still looks like an empty skeleton in many areas
- [x] section called "Installation" has a bunch of non-installation related stuff, should it be called "Getting Started"?
- [x] lots of ugly non-retina images still with ugly one pixel black border. let's use a light `box-shadow` instead and shrink the width to make it look ok on retina
- [x] use a decent modern font (Inter!)
- [x] "Resources" page needs TLC, we should put newer videos and much less Max overall, I'm unclear on whether "Community" and "Resources" are the right top-level items here as they are super overlappy (?) Maybe "Get started" and "Community"
- [x] screenshots aren't our best screenshots (resolution and content), carousel looks rough

## Should have
- [x] [minor/optional] the navbar could show the "active" item with the underline sticking after clicking it
- [x] headers in docs should have anchor tags for us to be able to direct-link to a specific section of FAQ entry

## Nice to have
- [ ] make docs landing page more visual (reuse carousel?) 
- [ ] theming / css is all over the place nice now, from antd defaults, to gatsby default to css files to emotion competing. I'd go with an antd-theme-first approach + emotion for consistency with Superset. This makes doing the polish work harder, fighting with competing CSS layers...
- [ ] code highlighting that follows the language

## Future
- [ ] docs search!? Really surprised that docz doesn't support this out of the box...

**Comment by ktmud** [comment]
For doc search, I know a lot of OSS (including AntD and React) uses https://www.algolia.com/ . I've also used it in one of my projects and it's awesome!
